### ISSUE TITLE
sample tests from qxf2 Page Object Model framework are not working 

### ISSUE THREAD

**Issue by rahul-bhave** [qxf2/qxf2-page-object-model#290]
Sample test from qxf2's Page Objects framework are not working.

After running test  `python -m pytest -k example_form --browser Chrome`  error ModuleNotFoundError: No module named '_pytest.resultlog' generated.

Below is tracelog-

```
$ python -m pytest -k example_form --browser Chrome
Traceback (most recent call last):
  File "C:\Program Files\Python38\lib\runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python38\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\Rahul Bhave Qxf2\code\rahul-qxf2\messaging\test_POM_24_11_2020\venv3\lib\site-packages\pytest\__main__.py", line 5, in <module>
    raise SystemExit(pytest.console_main())
  File "C:\Users\Rahul Bhave Qxf2\code\rahul-qxf2\messaging\test_POM_24_11_2020\venv3\lib\site-packages\_pytest\config\__init__.py", line 187, in console_main
    code = main()
  File "C:\Users\Rahul Bhave Qxf2\code\rahul-qxf2\messaging\test_POM_24_11_2020\venv3\lib\site-packages\_pytest\config\__init__.py", line 143, in main
    config = _prepareconfig(args, plugins)
  File "C:\Users\Rahul Bhave Qxf2\code\rahul-qxf2\messaging\test_POM_24_11_2020\venv3\lib\site-packages\_pytest\config\__init__.py", line 318, in _prepareconfig
    config = pluginmanager.hook.pytest_cmdline_parse(
  File "C:\Users\Rahul Bhave Qxf2\code\rahul-qxf2\messaging\test_POM_24_11_2020\venv3\lib\site-packages\pluggy\hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "C:\Users\Rahul Bhave Qxf2\code\rahul-qxf2\messaging\test_POM_24_11_2020\venv3\lib\site-packages\pluggy\manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "C:\Users\Rahul Bhave Qxf2\code\rahul-qxf2\messaging\test_POM_24_11_2020\venv3\lib\site-packages\pluggy\manager.py", line 84, in <lambda>
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File "C:\Users\Rahul Bhave Qxf2\code\rahul-qxf2\messaging\test_POM_24_11_2020\venv3\lib\site-packages\pluggy\callers.py", line 203, in _multicall
    gen.send(outcome)
  File "C:\Users\Rahul Bhave Qxf2\code\rahul-qxf2\messaging\test_POM_24_11_2020\venv3\lib\site-packages\_pytest\helpconfig.py", line 100, in pytest_cmdline_parse
    config = outcome.get_result()  # type: Config
  File "C:\Users\Rahul Bhave Qxf2\code\rahul-qxf2\messaging\test_POM_24_11_2020\venv3\lib\site-packages\pluggy\callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "C:\Users\Rahul Bhave Qxf2\code\rahul-qxf2\messaging\test_POM_24_11_2020\venv3\lib\site-packages\pluggy\callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "C:\Users\Rahul Bhave Qxf2\code\rahul-qxf2\messaging\test_POM_24_11_2020\venv3\lib\site-packages\_pytest\config\__init__.py", line 1003, in pytest_cmdline_parse
    self.parse(args)
  File "C:\Users\Rahul Bhave Qxf2\code\rahul-qxf2\messaging\test_POM_24_11_2020\venv3\lib\site-packages\_pytest\config\__init__.py", line 1280, in parse
    self._preparse(args, addopts=addopts)
  File "C:\Users\Rahul Bhave Qxf2\code\rahul-qxf2\messaging\test_POM_24_11_2020\venv3\lib\site-packages\_pytest\config\__init__.py", line 1172, in _preparse
    self.pluginmanager.load_setuptools_entrypoints("pytest11")
  File "C:\Users\Rahul Bhave Qxf2\code\rahul-qxf2\messaging\test_POM_24_11_2020\venv3\lib\site-packages\pluggy\manager.py", line 299, in load_setuptools_entrypoints
    plugin = ep.load()
  File "C:\Program Files\Python38\lib\importlib\metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "C:\Program Files\Python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "C:\Users\Rahul Bhave Qxf2\code\rahul-qxf2\messaging\test_POM_24_11_2020\venv3\lib\site-packages\_pytest\assertion\rewrite.py", line 171, in exec_module
    exec(co, module.__dict__)
  File "C:\Users\Rahul Bhave Qxf2\code\rahul-qxf2\messaging\test_POM_24_11_2020\venv3\lib\site-packages\pytest_rerunfailures.py", line 8, in <module>
    from _pytest.resultlog import ResultLog
ModuleNotFoundError: No module named '_pytest.resultlog'

```
steps to reproduce:
1. clone the repo.
2. Install virtual environment
3. Install requirements.txt
4. Run the test.

**Comment by rahul-bhave** [comment]
https://github.com/qxf2/qxf2-page-object-model/pull/292- This PR is opened for the fix of above issue

**Comment by rahul-bhave** [comment]
Issue closed as PR is merged.
